function ValidateFilterSpecification(Func, Type, f_lim, A_lim)
% Validate normalized filter limits before calculating design parameters.

if ~isnumeric(Func) || ~isscalar(Func) || ~isfinite(Func) || ...
        Func ~= floor(Func) || Func < 0 || Func > 3 || ...
        ~isnumeric(Type) || ~isscalar(Type) || ~isfinite(Type) || ...
        Type ~= floor(Type) || Type < 0 || Type > 1
    error('SignalProcessing:InvalidFilterSpecification', ...
        'Filter function and type must be supported integer values.');
end;

expectedLimitCount = 2 + 2 * (Func > 1);
if ~isnumeric(f_lim) || ~isvector(f_lim) || any(~isfinite(f_lim)) || ...
        numel(f_lim) ~= expectedLimitCount || any(f_lim <= 0) || ...
        any(f_lim >= 0.5) || any(diff(f_lim) <= 0) || ...
        ~isnumeric(A_lim) || ~isvector(A_lim) || any(~isfinite(A_lim)) || ...
        numel(A_lim) ~= expectedLimitCount || any(A_lim < 0)
    error('SignalProcessing:InvalidFilterSpecification', ...
        'Filter frequencies and attenuations must be finite, ordered valid limits.');
end;

if (Func == 0 && A_lim(2) <= A_lim(1)) || ...
        (Func == 1 && A_lim(1) <= A_lim(2)) || ...
        (Func == 2 && (A_lim(1) <= A_lim(2) || A_lim(4) <= A_lim(3))) || ...
        (Func == 3 && (A_lim(2) <= A_lim(1) || A_lim(3) <= A_lim(4)))
    error('SignalProcessing:InvalidFilterSpecification', ...
        'Passband attenuation must be lower than the corresponding stopband attenuation.');
end;
end